CXX = g++
CXXFLAGS = -std=c++17 

SRCDIR = src
SOURCES = $(SRCDIR)/main.cpp
EXECUTABLE = hash

all: $(EXECUTABLE)

$(EXECUTABLE): $(SOURCES)
	$(CXX) $(CXXFLAGS) $^ -o $@

clean:
	rm -f $(EXECUTABLE)
# // table size 161, block size 30 fd sum y fe redispersion close
#

#             // - u decide cuantos numeros aleatorios se añaden a la tabla, lo que hace es dcidir cuantas ejecucuiones se haceb de la funcion deexploracion, esto modifica el menu y lo que tiene que hacer es añadir valores nif?s aleatorios
#         //ademas se debe savbr cuantasveces se ejcutan las funciones de exploracion con una funcion,